# Generated by Django 2.1.dev20171216185936 on 2018-01-03 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_location', models.CharField(max_length=10)),
                ('destination_location', models.CharField(max_length=10)),
                ('quantity', models.FloatField()),
                ('value', models.FloatField()),
                ('stamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=10)),
                ('location_name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('Int', 'Internal'), ('Ext', 'External')], max_length=30)),
                ('bay', models.CharField(max_length=10)),
                ('note', models.TextField()),
                ('active', models.BooleanField()),
                ('stamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('active', models.BooleanField()),
                ('stamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(max_length=10)),
                ('transaction_type', models.CharField(max_length=10)),
                ('stamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=2000)),
                ('stamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='inventoryparts',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invent.Units'),
        ),
        migrations.AddField(
            model_name='inventhistory',
            name='transaction_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invent.InventTransactions'),
        ),
    ]
