# Generated by Django 2.1.dev20171216185936 on 2018-01-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventtransactions',
            name='transaction_direction',
            field=models.CharField(choices=[('+', 'Plus'), ('-', 'Minus'), ('0', 'Zero'), ('+v', 'IncrValue'), ('-v', 'DecrValue')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='inventhistory',
            name='stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventlocations',
            name='location_type',
            field=models.CharField(choices=[('Int', 'Internal'), ('Ext', 'External')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inventlocations',
            name='stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventoryparts',
            name='stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventtransactions',
            name='stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
