# Generated by Django 2.1.dev20171216185936 on 2018-01-18 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0003_customer_customerorderhead'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('stamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invent.Customer')),
            ],
        ),
    ]
