# Generated by Django 2.1.dev20171216185936 on 2018-01-19 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0005_auto_20180118_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartsInStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(null=True)),
                ('value', models.FloatField(null=True)),
                ('batch', models.CharField(blank=True, max_length=30, null=True)),
                ('stamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invent.InventLocations')),
                ('part_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invent.InventoryParts')),
            ],
        ),
        migrations.AddField(
            model_name='inventhistory',
            name='part_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invent.InventoryParts'),
        ),
    ]
