# Generated by Django 2.1.dev20171216185936 on 2018-01-19 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0006_auto_20180119_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationBay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bay', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventlocations',
            name='bay',
        ),
        migrations.AddField(
            model_name='locationbay',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='invent.InventLocations'),
        ),
    ]
